### ISSUE TITLE
Error loading component: 'target' is a required option

### ISSUE THREAD

**Issue by geoffbeier** [sveltejs/svelte-hmr#20]
I tried to kick the tires on snowpack, and I'm encountering an error when I try to use one of my components in dev mode. It seems to be related to svelte-hmr, I think.

This is the exception I see on the client:

```
<AddSymbolsDialog>
Error: 'target' is a required option
    at new SvelteComponentDev (http://localhost:8080/web_modules/svelte/internal.js:1628:19)
    at new AddSymbolsDialog (http://localhost:8080/_dist_/AddSymbolsDialog.js:185:3)
    at createProxiedComponent (http://localhost:8080/web_modules/svelte-hmr/runtime/hot-api-esm.js:201:9)
    at new ProxyComponent (http://localhost:8080/web_modules/svelte-hmr/runtime/hot-api-esm.js:440:20)
    at new Proxy<AddSymbolsDialog> (http://localhost:8080/web_modules/svelte-hmr/runtime/hot-api-esm.js:504:11)
    at create_if_block (http://localhost:8080/web_modules/svelte-simple-modal.js:609:25)
    at Object.p (http://localhost:8080/web_modules/svelte-simple-modal.js:963:17)
    at update (http://localhost:8080/web_modules/svelte-simple-modal.js:247:36)
    at flush (http://localhost:8080/web_modules/svelte-simple-modal.js:216:13)
```
It works fine running from a rollup bundle.

Full source to this project is [available here](https://git.sr.ht/~tuxpup/stock-toolkit/tree/snowpack) on the snowpack branch.

I put together a [very minimal project that reproduces the issue](https://git.sr.ht/~tuxpup/minimal-modal-hmr-test). To reproduce:

```
git clone https://git.sr.ht/~tuxpup/minimal-modal-hmr-test
cd minimal-modal-hmr-test
npm install
npm run dev
```

Then click on the "Show a big surprise" button.

To see how it should work:
```
npm run build
npm run serve
```
Then visit http://localhost:5000 and click the same button. You should see a modal with an OK button instead of the exception.

**Comment by rixo** [comment]
Do you know if this issue is still current?

**Comment by geoffbeier** [comment]
I had not looked since filing this, since I had to just move on for the
project I wanted it for. I just updated my [test project](
https://git.sr.ht/~tuxpup/minimal-modal-hmr-test) to current dependencies
and config requirements. This no longer seems to be a problem there. Nice!

**Comment by geoffbeier** [comment]
Looks good with the current versions of everything!
