### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by polRk** [sveltejs/svelte-hmr#30]
After component update i see

```
Failed to init component
<Sidebar>
TypeError: Cannot read property 'children' of undefined
    at removeNode (<anonymous>:118:31)
    at Object.block.d (<anonymous>:280:11)
    at destroy_component (http://localhost:8080/_snowpack/pkg/svelte.internal.v3.37.0.js:1336:32)
    at Sidebar.$destroy (http://localhost:8080/_snowpack/pkg/svelte.internal.v3.37.0.js:1443:5)
    at Sidebar.$destroy (http://localhost:8080/_snowpack/pkg/svelte.internal.v3.37.0.js:1552:11)
    at Sidebar.targetCmp.$replace (http://localhost:8080/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.3.js:178:20)
    at refreshComponent (http://localhost:8080/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.3.js:415:28)
    at ProxyAdapterDom.rerender (http://localhost:8080/_snowpack/pkg/svelte-hmr.runtime.proxy-adapter-dom.v0.13.3.js:196:5)
    at http://localhost:8080/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.3.js:644:9
    at Array.forEach (<anonymous>)
    ```

**Comment by polRk** [comment]
Vite, doesn't work too

**Comment by polRk** [comment]
After updating to the latest version, work's fine
